### ISSUE TITLE
Fetch more results without kicking user to a webpage

### ISSUE THREAD

**Issue by dgw** [dgw/sopel-wolfram#3]
Rizon's Internets bot (available on Bitbucket), for example, can print out the locations of airports if the input is an airport code; the definitions of English words; and a bunch more stuff that the Sopel module currently just spits out a URL for.

Maybe this is as simple as looking for more `output_ids`, maybe not.

**Comment by dgw** [comment]
Not quite that simple, but I do have a working prototype to test in production for a bit.

**Comment by maxpowa** [comment]
I implemented this in my older willie module a couple days ago, seems to work pretty well so far. https://github.com/maxpowa/inumuta-modules/commit/0218785e3de7554a72178214e28f669118f79888

Edit: Makes the assumption that pod 0 is the input interpretation and pod 1 is the result, which as far as I can tell, is the correct assumption.

**Comment by dgw** [comment]
Looks pretty similar to what I've got. Rizon's Internets module does it right.

I'll probably push this up in a day or two and bump a new minor version release…as soon as I can come up with a release name. (That's important to me for some reason.)
